format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$fill\
$time\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

[time]
disabled = false
format = '[$time]($style) '
style = "bold bright-black"

[fill]
symbol = ' '
style = ''

[directory]
read_only = " 󰌾"

[git_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

