#!/usr/bin/env bash

# Run all dotfiles installers.

# Exit the script immediately if any command exits with a non-zero status.
set -e

# Changes directory to the root of the dotfiles
cd "$(dirname $0)"/..

echo "› brew bundle"
brew bundle

# Find the installers and run them iteratively
echo "Running installers"
find . -path './oh-my-zsh' -prune -o -name install.sh -print | while read installer; do
  printf "  Running ${installer}"
  sh -c "${installer}"
done
echo "Finished installing"
